services:
  app-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: docker-project-backend:latest
    container_name: app-backend
    restart: on-failure
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    networks:
      - docker-project-local-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  app-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: docker-project-frontend:latest
    container_name: app-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VUE_APP_API_URL=http://app-backend:8081
    depends_on:
      app-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/momo-store/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    networks:
      - public
      - docker-project-local-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

networks:
  public:
    driver: bridge
  docker-project-local-net:
    driver: bridge
    internal: true
